version: "3.8"

services:
  db:
    image: postgis/postgis
    container_name: prayer_times_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mosque_db
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Change this to your email
      PGADMIN_DEFAULT_PASSWORD: admin123  # Change this password
    ports:
      - "5050:80"  # pgAdmin will be accessible on localhost:5050
    depends_on:
      - db      

volumes:
  postgres_data:
